import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Providers from '@/redux/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dstore',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <Navbar />
        <div className="mt-10">{children}</div>
        {/* {children} */}
        </Providers>
        </body>
    </html>
  )
};